import Head from "next/head";
import Carousel from "../components/carousel/carousel";
import Category from "../components/category/category";
import Header from "../components/header/header";
import Dreams from "../components/home";
import styles from "../styles/Home.module.css";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>tripperspk | Home</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Header />
        <Dreams />
        <Category />
        <Carousel />
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by North Aims
        </a>
      </footer>
    </div>
  );
}
